name: Tests

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "tests/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install poetry pytest pytest-asyncio
          poetry install

      - name: Run Tests
        run: poetry run pytest tests/
